# Generated by Django 5.2.17 on 2026-09-26 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('informed', 'informed'), ('share', 'share')], max_length=16)),
                ('version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='accounts.anonymousidentity')),
            ],
            options={
                'verbose_name': 'consent',
                'verbose_name_plural': 'consents',
                'db_table': 'consents',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['identity', 'kind', 'version'], name='consent_gate_idx')],
            },
        ),
    ]
