#!/usr/bin/env python3
"""Create `.env` from `.env.example` with fresh random secrets (T-004 amendment c).

`make env` calls this once. The two values that must never be shipped as-is are
generated locally; every other line is copied verbatim, comments included. The script
is idempotent: an existing `.env` is left untouched, and it never prints a secret.
"""

import pathlib
import secrets
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXAMPLE = ROOT / ".env.example"
TARGET = ROOT / ".env"

GENERATED = {
    "DJANGO_SECRET_KEY": lambda: secrets.token_urlsafe(48),
    "POSTGRES_PASSWORD": lambda: secrets.token_urlsafe(24),
}


def main() -> int:
    if not EXAMPLE.exists():
        print(f"FAIL: {EXAMPLE.name} is missing — cannot create .env")
        return 1
    if TARGET.exists():
        print(".env already exists — left untouched (delete it if you want new secrets)")
        return 0

    lines: list[str] = [
        "# Generated by scripts/init-env.py — local configuration, NEVER committed.",
        "# Secrets below are random per checkout; regenerate by deleting this file.",
    ]
    replaced: list[str] = []
    for line in EXAMPLE.read_text(encoding="utf-8").splitlines():
        key, sep, _value = line.partition("=")
        if sep and key.strip() in GENERATED:
            lines.append(f"{key}={GENERATED[key.strip()]()}")
            replaced.append(key.strip())
        else:
            lines.append(line)

    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    TARGET.chmod(0o600)
    print(f"created .env (0600) with random values for: {', '.join(sorted(replaced))}")
    print("next: `make up` for the stack, or `make check` for the gates")
    return 0


if __name__ == "__main__":
    sys.exit(main())
